name: Install, lint, test, build and size

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install, build and test
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
          yarn size
