name: Checks

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'package.json'
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      
      - name: Linting
        run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: yarn build

      - name: Size limit
        run: yarn size
      
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install all dependencies
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:coverage

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
