name: Update schedule

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update_schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install all dependencies
        run: yarn install --frozen-lockfile

      - name: Update schedule
        run: yarn updateSchedule

      - name: Set cridentials
        run: |
          git config --global user.name 'Automated Updater'
          git config --global user.email 'baitun@users.noreply.github.com'

      - name: Commit schedule
        run: yarn commitSchedule

      - name: Push changes
        run: |
          git pull --rebase
          git push
